SoftwareRouteGuideAPP/Models/Educations/Comments.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SoftwareRouteGuideAPP.Models.Educations
{
    public class Comments
    {
        public string content { get; set; }
        public string fullname { get; set; }
        public int educationID { get; set; }
    }
}

SoftwareRouteGuideAPP/Models/Educations/Education.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SoftwareRouteGuideAPP.Models.Educations
{
    public class Education
    {
        public int educationID { get; set; }
        public string Title { get; set; }
        public DateTime Date { get; set; }
        public string Type { get; set; }
        public string Photo1 { get; set; }
        public string Paragraph1 { get; set; }
        public string Paragraph2 { get; set; }
        public string Paragraph3 { get; set; }
        public string Subtitle1 { get; set; }
        public string Paragraph4 { get; set; }
        public string Paragraph5 { get; set; }
        public string Photo2 { get; set; }
        public string Paragraph6 { get; set; }
        public string Paragraph7 { get; set; }
        public string Paragraph8 { get; set; }
        public string Subtitle2 { get; set; }
        public string Paragraph9 { get; set; }
        public string Paragraph10 { get; set; }
        public int userID { get; set; }
        public string status { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }

    }
}

SoftwareRouteGuideAPP/Models/Educations/EducationAdd.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SoftwareRouteGuideAPP.Models.Educations
{
    public class EducationAdd
    {
        public string Title { get; set; }
        public string Type { get; set; }
        public string Photo1 { get; set; }
        public string Paragraph1 { get; set; }
        public string Paragraph2 { get; set; }
        public string Paragraph3 { get; set; }
        public string Subtitle1 { get; set; }
        public string Paragraph4 { get; set; }
        public string Paragraph5 { get; set; }
        public string Photo2 { get; set; }
        public string Paragraph6 { get; set; }
        public string Paragraph7 { get; set; }
        public string Paragraph8 { get; set; }
        public string Subtitle2 { get; set; }
        public string Paragraph9 { get; set; }
        public string Paragraph10 { get; set; }
        public int userID { get; set; }
    }
}

SoftwareRouteGuideAPP/Models/Educations/EducationCounts.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SoftwareRouteGuideAPP.Models.Educations
{
    public class EducationCounts
    {
        public Int32 educationCount { get; set; }
        public Int32 educationMonthlyCount { get; set; }
        public Int32 educationScore { get; set; }
    }
}

SoftwareRouteGuideAPP/Models/Educations/EducationDetailsViewModel.cs
using SoftwareRouteGuideAPP.Models.Teacher;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SoftwareRouteGuideAPP.Models.Educations
{
    public class EducationDetailsViewModel
    {

        public Education education { get; set; }
        public IEnumerable<Comments> comments { get; set; }
        public IEnumerable<Teachers> teacher { get; set; }
        
        public bool examStatus { get; set; }

    }
}

SoftwareRouteGuideAPP/Models/Educations/EducationUpdate.cs
namespace SoftwareRouteGuideAPP.Models.Educations
{
    public class EducationUpdate
    {
        public int educationID { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public string Photo1 { get; set; }
        public string Paragraph1 { get; set; }
        public string Paragraph2 { get; set; }
        public string Paragraph3 { get; set; }
        public string Subtitle1 { get; set; }
        public string Paragraph4 { get; set; }
        public string Paragraph5 { get; set; }
        public string Photo2 { get; set; }
        public string Paragraph6 { get; set; }
        public string Paragraph7 { get; set; }
        public string Paragraph8 { get; set; }
        public string Subtitle2 { get; set; }
        public string Paragraph9 { get; set; }
        public string Paragraph10 { get; set; }
    }
}

SoftwareRouteGuideAPP/Models/Educations/EducationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SoftwareRouteGuideAPP.Models.Educations
{
    public class EducationViewModel
    {

        public IEnumerable<Education> educationFirst6 { get; set; }
        public IEnumerable<Education> educationLast2 { get; set; }
    }
}

SoftwareRouteGuideAPP/Models/Educations/Exam.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SoftwareRouteGuideAPP.Models.Educations
{
    public class Exam
    {
        public int questionID { get; set; }
        public string Description { get; set; }
        public string choice1 { get; set; }
        public string choice2 { get; set; }
        public string choice3 { get; set; }
        public string trueAnswer { get; set; }
        public int educationID { get; set; }
    }
}

SoftwareRouteGuideAPP/Models/Educations/SuggestStatusDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SoftwareRouteGuideAPP.Models.Educations
{
    public class SuggestStatusDto
    {
        public int educationID { get; set; }
        public string status { get; set; }
    }
}

SoftwareRouteGuideAPP/Models/Teacher/ApplicationDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SoftwareRouteGuideAPP.Models.Teacher
{
    public class ApplicationDetails
    {
        public int userID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
    }
}

SoftwareRouteGuideAPP/Models/Teacher/ApplicationStatusDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SoftwareRouteGuideAPP.Models.Teacher
{
    public class ApplicationStatusDto
    {
        public int userID { get; set; }
        public string status { get; set; }
    }
}

SoftwareRouteGuideAPP/Models/Teacher/TeacherApplication.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SoftwareRouteGuideAPP.Models.Teacher
{
    public class TeacherApplication
    {
        public string Message { get; set; }
        public int userID { get; set; }
    }
}

SoftwareRouteGuideAPP/Models/Teacher/Teachers.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SoftwareRouteGuideAPP.Models.Teacher
{
    public class Teachers
    {
        public int userID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Telephone { get; set; }
        public string Photo { get; set; }
    }
}

SoftwareRouteGuideAPP/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json.Linq;
using SoftwareRouteGuideAPP.Helpers;
using SoftwareRouteGuideAPP.Models.Educations;
using SoftwareRouteGuideAPP.Models.Teacher;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SoftwareRouteGuideAPP.Models;
using Newtonsoft.Json;

namespace SoftwareRouteGuideAPP.Controllers
{
    public class TeacherController : Controller
    {
        WebRequestHelper webRequestHelper;
        public TeacherController()
        {
            webRequestHelper = new();
        }

        [HttpGet]
        public async Task<IActionResult> AllTeachers()
        {
            var educations = await webRequestHelper.GetBuilder("Teacher/AllTeachers");
            var responseData = JObject.Parse(educations).SelectToken("data").ToObject<List<Teachers>>();

            return View(responseData);
        }

        [HttpGet]
        public async Task<IActionResult> AllApplications()
        {
            var educations = await webRequestHelper.GetBuilder("Teacher/AllApplications");
            var responseData = JObject.Parse(educations).SelectToken("data").ToObject<List<ApplicationDetails>>();

            return View(responseData);
        }

        [HttpGet]
        public async Task<IActionResult> Educations(int id)
        {
            if (HttpContext.Session.GetInt32("userID") == id)
            {
                var educations = await webRequestHelper.GetBuilder($"Education/GetByTeacherId?id={id}");
                var responseData = JsonConvert.DeserializeObject<ResponseModel<List<Education>>>(educations);
                var viewData = new List<Education>();
                
                if (responseData.success)
                    viewData = JObject.Parse(educations).SelectToken("data").ToObject<List<Education>>();

                return View(viewData);
            }
            else
            {
                return View(null);
            }

        }

        [HttpGet]
        public IActionResult TeacherApplication()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> TeacherApplication(TeacherApplication teacher)
        {
            var query = new { teacher.Message, teacher.userID };
            var response = await webRequestHelper.PostBuilder("Teacher/TeacherApplication", query); //HttpRequest

            return RedirectToAction("TeacherApplication");
        }

        public async Task<IActionResult> Approval(int id)
        {
            var response = await webRequestHelper.PostBuilder("Teacher/ApproveApplication?id="+id, ""); //HttpRequest

            return RedirectToAction("AllApplications");
        }

        public async Task<IActionResult> Rejected(int id)
        {
            var response = await webRequestHelper.PostBuilder("Teacher/RejectApplication?id=" + id, ""); //HttpRequest

            return RedirectToAction("AllApplications");
        }
    }
}

SoftwareRouteGuideAPP/Views/Teacher/AllApplications.cshtml
@{
    ViewData["Title"] = "Eğitmenlik Başvuruları";
}
@using SoftwareRouteGuideAPP.Models.Teacher
@model List<ApplicationDetails>
<section class="cta">
    <div class="cta-content">
        <div class="container px-5">
            <h2 class="text-light display-1 lh-1 mb-4">
                Eğitmenlerini özenle seçmelisin.
                <br />
                Detaylar aşağıdadır.
            </h2>
        </div>
    </div>
</section>
<h2 class="text-dark display-4 mb-4 text-center mt-3">
    Eğitmenlik Başvuruları Listesi
</h2>
<div class="row gx-5 text-center mx-5">
    @foreach (var app in Model)
    {
        <div class="card mx-3">
            <h5 class="card-header">@app.Name  @app.Surname</h5>
            <div class="card-body mb">
                <h5 class="card-title">@app.Email</h5>
                <p class="card-text">@app.Message</p>
                <a href="/Teacher/Approval/@app.userID" class="btn btn-outline-success">Başvuruyu Onayla</a>
                <a href="/Teacher/Rejected/@app.userID" class="btn btn-outline-danger">Başvuruyu Reddet</a>
            </div>
        </div>
    }


</div>

SoftwareRouteGuideAPP/Views/Teacher/AllTeachers.cshtml
@{
    ViewData["Title"] = "Eğitmenler";
    string myMessage;
}
@using Microsoft.AspNetCore.Http
@using SoftwareRouteGuideAPP.Models.Teacher
@model List<Teachers>
<section class="teacher" style="background-image: url('../img/teacher.jpg')">
    <div class="teacher-content">
        <div class="container px-5">
            <h2 class="text-light display-1 lh-1 mb-4">
                Eğitim sınırsızdır.
                <br />
                Eğitmenlerimizle tanış.
            </h2>
            @if (@Context.Session.GetInt32("userID").HasValue && @Context.Session.GetString("userType") == "User")
            {
                <a class="btn btn-outline-light py-3 px-4 rounded-pill" href="/Education/EducationProposal" target="_blank">Ücretsiz Eğitim Önerisinde Bulun</a>
            }
            
        </div>
    </div>
</section>

<section class="testimonials text-center bg-light">
    <div class="container">
        <h2 class="mb-5 text-dark lead" style="font-size: 50px;">Eğitmenler Listesi</h2>
        <div class="row">
            @foreach (var teachers in Model)
            {
                myMessage = "https://wa.me/90" + @teachers.Telephone + "?text=SRG%20aracılığı%20ile%20size%20ulaştım%20selam";

                <div class="col-lg-4 mt-5">
                    <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                        <img class="img-fluid rounded-circle mb-3" src="~/img/teacherIcon.png" style="height: 162px; width: 162px;" alt="..." />
                        <h5 class="text-danger">@teachers.Name @teachers.Surname</h5>
                        <p class="font-weight-light  text-dark lead">Software Route Guide eğitmenleri ile dilediğiniz vakit WhatsApp üzerinden iletişime geçebilirsiniz.</p>
                        @if (@Context.Session.GetInt32("userID").HasValue && @Context.Session.GetString("userType") == "User")
                        {
                            <a href="@myMessage" class="btn btn-outline-dark mb-5">Mesaj At</a>
                        }
                    </div>
                </div>
            }

        </div>
    </div>
</section>

<aside class="text-center bg-dark">
    <div class="container px-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-xl-8">
                <div class="h2 fs-1 text-light mb-4">"Her seviyeden yazılımcılar için eğitim serisi, hem de tek bir platformda!"</div>
                <img src="~/img/srglogo2.png" alt="..." style="height: 3rem" />
            </div>
        </div>
    </div>
</aside> 

SoftwareRouteGuideAPP/Views/Teacher/Educations.cshtml
@{
    ViewData["Title"] = "Tüm Eğitimler";
}
@using Microsoft.AspNetCore.Http
@using SoftwareRouteGuideAPP.Models.Educations
@model List<Education>
<section class="edc" style="background-image: url('../img/software.jpg')">
    <div class="edc-content">
        <div class="container px-5">
            <h2 class="text-light display-1 lh-1 mb-4">
                Günün en doğru kararı.
                <br />
                Öğrenmeye başlamaktır.
            </h2>
        </div>
    </div>
</section>


<section class="py-5">
    <div class="container px-5">
        <h2 class="fw-bolder fs-5 mb-4">Tüm Eğitimler</h2>

        <div class="row gx-5">
            @if (Model != null)
            {
                @if (Model.Count > 0)
                {
                    @foreach (var education in Model)
                    {
                        <div class="col-lg-4 mb-5">
                            <div class="card h-100 shadow border-0 edccard">
                                <img class="card-img-top" style="height: 100%;" src="@education.Photo1" alt="..." />
                                <div class="card-body p-4">
                                    <div class="badge bg-primary bg-gradient rounded-pill mb-2">@education.Type</div>
                                    <a class="text-decoration-none link-dark stretched-link"
                            href="/Education/EducationDetails/@education.educationID">
                                        <div class="h5 card-title mb-3"
                                style="width: 100%; overflow: hidden; display: inline-block; text-overflow: ellipsis; white-space: nowrap; ">
                                            @education.Title</div>
                                    </a>
                                    <p class="card-text mb-0"
                            style="width: 100%; overflow: hidden; display: inline-block; text-overflow: ellipsis; white-space: nowrap; ">
                                        @education.Subtitle1</p>
                                </div>
                                <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                                    <div class="d-flex align-items-end justify-content-between">
                                        <div class="d-flex align-items-center">
                                            <img class="rounded-circle me-3" style="height: 40px; width: 40px;" src="~/img/teacherIcon.png" alt="..." />
                                            <div class="small">
                                                <div class="fw-bold">@education.Name @education.Surname</div>
                                                <div class="text-muted">@education.Date.ToString("dd.MM.yyyy") </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>

                            <div class="" >
                                <a class="btn btn-outline-danger" href="/Education/Delete/@education.educationID">Eğitimi Sil</a>
                                <a class="btn btn-outline-warning" href="/Education/Update/@education.educationID">
                                    Eğitimi
                                    Düzenle
                                </a>
                                <a class="btn btn-outline-success" href="/Exam/Add/@education.educationID">Sınav Oluştur</a>

                            </div>
                        </div>
                    }

                }
                else if (Model.Count == 0)
                {
                    <div class="alert alert-danger" role="alert">
                        Hiç eğitiminiz bulunamadı!
                    </div>
                }
            }
            else
            {
                <div class="alert alert-danger" role="alert">
                    Bu sayfaya erişemezsiniz!
                </div>
            }



        </div>

    </div>
</section>
<aside class="text-center bg-dark">
    <div class="container px-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-xl-8">
                <div class="h2 fs-1 text-light mb-4">"Her seviyeden yazılımcılar için eğitim serisi, hem de tek bir
                    platformda!"</div>
                <img src="~/img/srglogo2.png" alt="..." style="height: 3rem" />
            </div>
        </div>
    </div>
</aside>

SoftwareRouteGuideAPP/Views/Teacher/TeacherApplication.cshtml
@model SoftwareRouteGuideAPP.Models.Teacher.TeacherApplication
@using Microsoft.AspNetCore.Http
<section class="px-5">
    <div class="container px-5">
        <!-- Contact form-->
        <div class=" rounded-3 py-5 px-4 px-md-5 ">
            <div class="text-center mb-5">
                <h1 class="fw-bolder">Eğitmenlik Başvurusu Yap</h1>
                <p class="lead fw-normal text-muted mb-0">Eğitmen olmak için talebini mesaj kısmına yaz, incelemeye alınacaksın..</p>
            </div>
            <div class="row gx-5 justify-content-center">
                <div class="col-lg-8 col-xl-6">
                    <form method="post" asp-controller="Teacher" asp-action="TeacherApplication">

                        <div class="form-floating mb-3">
                            <textarea class="form-control" id="message" asp-for="Message" type="text" placeholder="Enter your message here..." style="height: 10rem" data-sb-validations="required"></textarea>
                            <label for="message">Mesajınız</label>
                        </div>
                        <input type="hidden" asp-for="userID" value="@Context.Session.GetInt32("userID")" />
                        <div class="d-grid"><button class="btn btn-success btn-lg" type="submit">Gönder</button>
                    </form>
                </div>
            </div>
        </div>
        <!-- Contact cards-->

    </div>
</section>